### ISSUE TITLE
Circular import error

### ISSUE THREAD

**Issue by ccrismancox** [b45ch1/pyadolc#35]
Has anyone else run into this problem? It just started for me this last week when trying to reinstall on a Ubuntu 20.04 system. Everything appears to install fine, but then I get this error when trying to import 
```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adolc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cox/pyopterf/pyadolc/adolc/__init__.py", line 1, in <module>
    from . import _adolc
ImportError: cannot import name '_adolc' from partially initialized module 'adolc' (most likely due to a circular import) (/home/cox/pyopterf/pyadolc/adolc/__init__.py)
>>> 
```

**Comment by ccrismancox** [comment]
Solved it by completely removing any traces of pyadolc from my machine and starting from scratch
